### ISSUE TITLE
`violation_json': undefined method `first_line' for #<RuboCop::Cop::Lint::Syntax::PseudoSourceRange:0x007f87ff6e58a0> (NoMethodError)

### ISSUE THREAD

**Issue by mshappe** [codeclimate/codeclimate-rubocop#1]
```

error: (CC::Analyzer::Engine::EngineFailure) engine rubocop failed with status 1 and stderr "/usr/src/app/lib/cc/engine/rubocop.rb:79:in `violation_json': undefined method `first_line' for #<RuboCop::Cop::Lint::Syntax::PseudoSourceRange:0x007f87ff6e58a0> (NoMethodError)\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:25:in `block (3 levels) in run'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:24:in `each'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:24:in `block (2 levels) in run'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:19:in `each'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:19:in `block in run'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:16:in `chdir'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:16:in `run'\n\tfrom /usr/src/app/bin/codeclimate-rubocop:6:in `<main>'\n"

```

**Comment by GordonDiggs** [comment]
@mshappe thanks! A fix for this is in our roadmap

**Comment by mshappe** [comment]
@GordonDiggs Thanks. Sorry for such a terse report :smile: In retrospect I probably should have included more detail, but I figured it was fairly obvious -- I was running the new codeclimate CLI, and bumped into this. I get this on every repo I've tried it on so far.

**Comment by GordonDiggs** [comment]
@mshappe This should be fixed now! If you re-run `codeclimate engines:install` before your next `codeclimate analyze` command you should get the new version of the image.

**Comment by mshappe** [comment]
Confirmed, and thank you!
