### ISSUE TITLE
Rubocop parser error 9/8

### ISSUE THREAD

**Issue by abbyarmada** [codeclimate/codeclimate-rubocop#103]
User is seeing this error in the Rubocop step of one of their builds. It is currently stopping their analysis:

```Digest: sha256:6b344761255511f8c58a76bdff93ea59a88179f0612ab3a49d27744c38fa31f4
Status: Downloaded newer image for registry.prod.codeclimate.net/codeclimate/codeclimate-rubocop:b319
/usr/local/bundle/gems/parser-2.3.3.1/lib/parser/source/range.rb:182:in `join': undefined method `begin_pos' for nil:NilClass (NoMethodError)
	from /usr/local/bundle/gems/parser-2.3.3.1/lib/parser/builders/default.rb:1191:in `join_exprs'
	from /usr/local/bundle/gems/parser-2.3.3.1/lib/parser/builders/default.rb:1273:in `collection_map'
	from /usr/local/bundle/gems/parser-2.3.3.1/lib/parser/builders/default.rb:1026:in `begin_body'
	from /usr/local/bundle/gems/parser-2.3.3.1/lib/parser/ruby21.rb:3366:in `_reduce_9'
	from /usr/local/lib/ruby/2.3.0/racc/parser.rb:259:in `_racc_do_parse_c'
	from /usr/local/lib/ruby/2.3.0/racc/parser.rb:259:in `do_parse'
	from /usr/local/bundle/gems/parser-2.3.3.1/lib/parser/base.rb:162:in `parse'
	from /usr/local/bundle/gems/parser-2.3.3.1/lib/parser/base.rb:209:in `tokenize'
	from /usr/local/bundle/gems/rubocop-0.46.0/lib/rubocop/processed_source.rb:99:in `tokenize'
	from /usr/local/bundle/gems/rubocop-0.46.0/lib/rubocop/processed_source.rb:94:in `parse'
	from /usr/local/bundle/gems/rubocop-0.46.0/lib/rubocop/processed_source.rb:36:in `initialize'
	from /usr/local/bundle/gems/rubocop-0.46.0/lib/rubocop/processed_source.rb:17:in `new'
	from /usr/local/bundle/gems/rubocop-0.46.0/lib/rubocop/processed_source.rb:17:in `from_file'
	from /usr/src/app/lib/cc/engine/source_file.rb:27:in `processed_source'
	from /usr/src/app/lib/cc/engine/source_file.rb:14:in `inspect'
	from /usr/src/app/lib/cc/engine/rubocop.rb:36:in `block (2 levels) in run'
	from /usr/src/app/lib/cc/engine/rubocop.rb:30:in `each'
	from /usr/src/app/lib/cc/engine/rubocop.rb:30:in `block in run'
	from /usr/src/app/lib/cc/engine/rubocop.rb:29:in `chdir'
	from /usr/src/app/lib/cc/engine/rubocop.rb:29:in `run'
	from /usr/src/app/bin/codeclimate-rubocop:17:in `<main>'
```

Will pass on more info if you need it.

**Comment by abbyarmada** [comment]
cc @katwchen

**Comment by GordonDiggs** [comment]
One thing to try would be using the `rubocop-0-50` channel. [This](https://github.com/bbatsov/rubocop/issues/4803#issuecomment-332525106) looks potentially related

**Comment by abbyarmada** [comment]
For reference, you'll need to add a `.codeclimate.yml` to the repo. For more info check out our docs here:
[Configuring Your Code Climate Analysis](https://docs.codeclimate.com/docs/configuring-your-code-climate-analysis)
[Using Newer Versions of Rubocop](https://docs.codeclimate.com/docs/rubocop#section-using-rubocop-s-newer-versions)

**Comment by wfleming** [comment]
I think we can close this: the related rubocop issues are all closed, and this issue doesn't contain reproduction details. If this is still happening we should re-open with reproduction details or track internally if details can't be posted here.
