### ISSUE TITLE
No such file or directory @ realpath_rec - /code/public/assets (Errno::ENOENT)

### ISSUE THREAD

**Issue by mikz** [codeclimate/codeclimate-rubocop#55]
```
/usr/src/app/lib/cc/engine/file_list_resolver.rb:47:in `realpath': No such file or directory @ realpath_rec - /code/public/assets (Errno::ENOENT)
	from /usr/src/app/lib/cc/engine/file_list_resolver.rb:47:in `realpath'
	from /usr/src/app/lib/cc/engine/file_list_resolver.rb:47:in `block in absolute_include_paths'
	from /usr/src/app/lib/cc/engine/file_list_resolver.rb:47:in `map'
	from /usr/src/app/lib/cc/engine/file_list_resolver.rb:47:in `absolute_include_paths'
	from /usr/src/app/lib/cc/engine/file_list_resolver.rb:32:in `include_based_files_to_inspect'
	from /usr/src/app/lib/cc/engine/file_list_resolver.rb:13:in `expanded_list'
	from /usr/src/app/lib/cc/engine/rubocop.rb:47:in `files_to_inspect'
	from /usr/src/app/lib/cc/engine/rubocop.rb:27:in `block in run'
	from /usr/src/app/lib/cc/engine/rubocop.rb:26:in `chdir'
	from /usr/src/app/lib/cc/engine/rubocop.rb:26:in `run'
	from /usr/src/app/bin/codeclimate-rubocop:14:in `<main>'
```

This happens in our build. I don't see any place where we would refer to `public/assets`. We don't have `include_paths` in the yaml config at all.

When running locally, it fails the same, just with different folder:

```
/usr/src/app/lib/cc/engine/file_list_resolver.rb:23:in `realpath': No such file or directory @ realpath_rec - /deploy (Errno::ENOENT)
```

**Comment by wfleming** [comment]
@mikz Sorry about that: we've released a fix for this now. Can you please do a `codeclimate engines:install` to get the newest `codeclimate-rubocop` build, and see if that fixes this issue for you?

**Comment by wfleming** [comment]
Going to close this: we believe it's fixed. Please feel free to comment & re-open if you're still experiencing this problem.

**Comment by mikz** [comment]
Solved! Thanks.
