### ISSUE TITLE
codeclimate-rubocop:rubocop-0-48 active-support version causing errors

### ISSUE THREAD

**Issue by watsonjon** [codeclimate/codeclimate-rubocop#97]
I'm trying to use the latest version of RuboCop with the channel `rubocop-0-48` but at run-time this error is given:

```
error: (CC::Analyzer::Engine::EngineFailure) engine rubocop:rubocop-0-48 failed with status 1 and stderr 
/usr/local/bundle/gems/activesupport-5.1.0/lib/active_support/core_ext/date_time/compatibility.rb:6:in `<class:DateTime>': undefined method `remove_possible_method' for DateTime:Class (NoMethodError)
Did you mean?  remove_method
	from /usr/local/bundle/gems/activesupport-5.1.0/lib/active_support/core_ext/date_time/compatibility.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/bundle/gems/activesupport-5.1.0/lib/active_support/core_ext/date_time.rb:4:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /usr/local/bundle/gems/activesupport-5.1.0/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
	from /usr/local/bundle/gems/activesupport-5.1.0/lib/active_support/core_ext.rb:1:in `each'
	from /usr/local/bundle/gems/activesupport-5.1.0/lib/active_support/core_ext.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/src/app/lib/cc/engine/rubocop.rb:17:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/src/app/bin/codeclimate-rubocop:8:in `<main>'
```

It looks like this was fixed several days ago: https://github.com/rails/rails/commit/001fc80d8784670277af3b9dd3d22f16cbf965f9

**Comment by maxjacobson** [comment]
@watsonjon thanks for the report. I'm not sure why our tests didn't catch this! Just shipped an update to address this. Will you let us know if you have any other issues?

**Comment by watsonjon** [comment]
@maxjacobson thank you! it works great now!
